# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sqrt_ <- function(X) {
    .Call('_optAM_sqrt_', PACKAGE = 'optAM', X)
}

optgenam3 <- function(currentPresenceMatrix, consecutiveSuitabilityMatrix, costMatrix, migrationKernel, threshold, confidence, npop, nsur, ngen) {
    .Call('_optAM_optgenam3', PACKAGE = 'optAM', currentPresenceMatrix, consecutiveSuitabilityMatrix, costMatrix, migrationKernel, threshold, confidence, npop, nsur, ngen)
}

index_random_choice_non_uniform <- function(ununiform_probabilities0) {
    .Call('_optAM_index_random_choice_non_uniform', PACKAGE = 'optAM', ununiform_probabilities0)
}

generate_permutation4 <- function(permutation_size, ununiform_probabilities0) {
    .Call('_optAM_generate_permutation4', PACKAGE = 'optAM', permutation_size, ununiform_probabilities0)
}

proba_matrix_mult3 <- function(A, B) {
    .Call('_optAM_proba_matrix_mult3', PACKAGE = 'optAM', A, B)
}

rcpp_global_suitable_sites <- function(consecutiveSuitabilityMatrix) {
    .Call('_optAM_rcpp_global_suitable_sites', PACKAGE = 'optAM', consecutiveSuitabilityMatrix)
}

rcpp_global_suitable_coordinates <- function(globalSuitableSites) {
    .Call('_optAM_rcpp_global_suitable_coordinates', PACKAGE = 'optAM', globalSuitableSites)
}

rcpp_local_transition_matrix <- function(globalSuitableSites, globalSuitableCoordinates, migrationKernel) {
    .Call('_optAM_rcpp_local_transition_matrix', PACKAGE = 'optAM', globalSuitableSites, globalSuitableCoordinates, migrationKernel)
}

rcpp_transition_matrices <- function(consecutiveSuitabilityMatrix, localTransitionMatrix, globalSuitableCoordinates) {
    .Call('_optAM_rcpp_transition_matrices', PACKAGE = 'optAM', consecutiveSuitabilityMatrix, localTransitionMatrix, globalSuitableCoordinates)
}

rcpp_colonisation_matrices <- function(transitionMatrices) {
    .Call('_optAM_rcpp_colonisation_matrices', PACKAGE = 'optAM', transitionMatrices)
}

rcpp_viable_sites <- function(colonisationMatrices) {
    .Call('_optAM_rcpp_viable_sites', PACKAGE = 'optAM', colonisationMatrices)
}

rcpp_viable_triplets <- function(viableSites, colonisationMatrices, globalSuitableCoordinates, globalSuitableSites, costMatrix) {
    .Call('_optAM_rcpp_viable_triplets', PACKAGE = 'optAM', viableSites, colonisationMatrices, globalSuitableCoordinates, globalSuitableSites, costMatrix)
}

rcpp_viable_values <- function(viablesTriplets, viableSites, globalSuitableSites, colonisationMatrices) {
    .Call('_optAM_rcpp_viable_values', PACKAGE = 'optAM', viablesTriplets, viableSites, globalSuitableSites, colonisationMatrices)
}

rcpp_eval_current_prob <- function(threshold, currentPresenceMatrix, colonisationMatrices, globalSuitableSites) {
    .Call('_optAM_rcpp_eval_current_prob', PACKAGE = 'optAM', threshold, currentPresenceMatrix, colonisationMatrices, globalSuitableSites)
}

rcpp_pheromons <- function(viablesTriplets) {
    .Call('_optAM_rcpp_pheromons', PACKAGE = 'optAM', viablesTriplets)
}

rcpp_generate_population <- function(pheromons, globalSuitableSites, npop, nbtoplant) {
    .Call('_optAM_rcpp_generate_population', PACKAGE = 'optAM', pheromons, globalSuitableSites, npop, nbtoplant)
}

rcpp_algorithm_opt <- function(pheromons, viablesTriplets, population0, costMatrix, currentPresenceMatrix, colonisationMatrices, globalSuitableSites, viablesValues, threshold, confidence, npop, nsur, ngen, nbtoplant) {
    .Call('_optAM_rcpp_algorithm_opt', PACKAGE = 'optAM', pheromons, viablesTriplets, population0, costMatrix, currentPresenceMatrix, colonisationMatrices, globalSuitableSites, viablesValues, threshold, confidence, npop, nsur, ngen, nbtoplant)
}

rcpp_result_to_choice <- function(lastPopulation, viablesTriplets) {
    .Call('_optAM_rcpp_result_to_choice', PACKAGE = 'optAM', lastPopulation, viablesTriplets)
}

rcppeigen_hello_world <- function() {
    .Call('_optAM_rcppeigen_hello_world', PACKAGE = 'optAM')
}

rcppeigen_outerproduct <- function(x) {
    .Call('_optAM_rcppeigen_outerproduct', PACKAGE = 'optAM', x)
}

rcppeigen_innerproduct <- function(x) {
    .Call('_optAM_rcppeigen_innerproduct', PACKAGE = 'optAM', x)
}

rcppeigen_bothproducts <- function(x) {
    .Call('_optAM_rcppeigen_bothproducts', PACKAGE = 'optAM', x)
}

timesTwo2 <- function(x) {
    .Call('_optAM_timesTwo2', PACKAGE = 'optAM', x)
}

timesFour <- function(x) {
    .Call('_optAM_timesFour', PACKAGE = 'optAM', x)
}

